# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0003_auto_20170626_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residency.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residency.Project'),
        ),
    ]
