# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0004_auto_20170627_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stat',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
