# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0006_auto_20170627_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residency.Project'),
        ),
    ]
