# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0008_auto_20170627_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='specs',
            field=models.CharField(default=None, max_length=2500),
            preserve_default=False,
        ),
    ]
