# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0010_auto_20170627_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residency.Team'),
        ),
    ]
