# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0013_auto_20170703_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
