# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0016_auto_20170703_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=45)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residency.Acc')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residency.Project')),
            ],
        ),
    ]
