# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0017_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamSched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residency.Team')),
            ],
        ),
    ]
