# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0018_teamsched'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsched',
            name='sched',
            field=models.CharField(default='1 07:30 10:45', max_length=15),
            preserve_default=False,
        ),
    ]
