# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0019_teamsched_sched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamsched',
            name='sched',
        ),
        migrations.AddField(
            model_name='teamsched',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsched',
            name='end',
            field=models.CharField(default='10:30', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsched',
            name='start',
            field=models.CharField(default='07:30', max_length=5),
            preserve_default=False,
        ),
    ]
