# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residency', '0020_auto_20170705_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cubes',
            field=models.CharField(default='LEXELL', max_length=20),
            preserve_default=False,
        ),
    ]
